In [128]:
# import libraries
import pandas as pd
import requests

In [129]:
#import csv file to environ
def data():
    data=pd.read_csv("all_countries.csv")
    return data

In [130]:
# import api data to environ
def data1():
    demo = requests.get("https://api.worldbank.org/v2/country/?format=json", headers={"Accept": "application/json"})
    response = demo.json()
    data1=pd.json_normalize(response[1])
    return data1

In [131]:
data()

              country     capital    region  ... population  iso2  iso3
0           Lithuania     Vilnius    Europe  ...    2794700    LT   LTU
1               Chile    Santiago  Americas  ...   19116209    CL   CHL
2               Benin  Porto-Novo    Africa  ...   12123198    BJ   BEN
3    Falkland Islands     Stanley  Americas  ...       2563    FK   FLK
4             Georgia     Tbilisi      Asia  ...    3714000    GE   GEO
..                ...         ...       ...  ...        ...   ...   ...
245         Palestine   Jerusalem      Asia  ...    4803269    PS   PSE
246            Russia      Moscow    Europe  ...  144104080    RU   RUS
247        Azerbaijan        Baku      Asia  ...   10110116    AZ   AZE
248      South Africa    Pretoria    Africa  ...   59308690    ZA   ZAF
249            Turkey      Ankara      Asia  ...   84339067    TR   TUR

[250 rows x 8 columns]

In [132]:
data1()

     id iso2Code  ... lendingType.iso2code lendingType.value
0   ABW       AW  ...                   XX    Not classified
1   AFE       ZH  ...                             Aggregates
2   AFG       AF  ...                   XI               IDA
3   AFR       A9  ...                             Aggregates
4   AFW       ZI  ...                             Aggregates
5   AGO       AO  ...                   XF              IBRD
6   ALB       AL  ...                   XF              IBRD
7   AND       AD  ...                   XX    Not classified
8   ARB       1A  ...                             Aggregates
9   ARE       AE  ...                   XX    Not classified
10  ARG       AR  ...                   XF              IBRD
11  ARM       AM  ...                   XF              IBRD
12  ASM       AS  ...                   XX    Not classified
13  ATG       AG  ...                   XF              IBRD
14  AUS       AU  ...                   XX    Not classified
15  AUT       AT  ...                   XX    Not classified
16  AZE       AZ  ...                   XF              IBRD
17  BDI       BI  ...                   XI               IDA
18  BEA       B4  ...                             Aggregates
19  BEC       B7  ...                             Aggregates
20  BEL       BE  ...                   XX    Not classified
21  BEN       BJ  ...                   XI               IDA
22  BFA       BF  ...                   XI               IDA
23  BGD       BD  ...                   XI               IDA
24  BGR       BG  ...                   XF              IBRD
25  BHI       B1  ...                             Aggregates
26  BHR       BH  ...                   XX    Not classified
27  BHS       BS  ...                   XX    Not classified
28  BIH       BA  ...                   XF              IBRD
29  BLA       B2  ...                             Aggregates
30  BLR       BY  ...                   XF              IBRD
31  BLZ       BZ  ...                   XH             Blend
32  BMN       B3  ...                             Aggregates
33  BMU       BM  ...                   XX    Not classified
34  BOL       BO  ...                   XF              IBRD
35  BRA       BR  ...                   XF              IBRD
36  BRB       BB  ...                   XF              IBRD
37  BRN       BN  ...                   XX    Not classified
38  BSS       B6  ...                             Aggregates
39  BTN       BT  ...                   XI               IDA
40  BWA       BW  ...                   XF              IBRD
41  CAA       C9  ...                             Aggregates
42  CAF       CF  ...                   XI               IDA
43  CAN       CA  ...                   XX    Not classified
44  CEA       C4  ...                             Aggregates
45  CEB       B8  ...                             Aggregates
46  CEU       C5  ...                             Aggregates
47  CHE       CH  ...                   XX    Not classified
48  CHI       JG  ...                   XX    Not classified
49  CHL       CL  ...                   XF              IBRD

[50 rows x 18 columns]

In [133]:
print(data)

<function data at 0x7ffacc74cea0>

In [104]:
# Clean data csv file
def cleaned_data(data=data()):
    data = data.fillna("Unknown")
    data = data.drop_duplicates()
    data.columns = data.columns.str.strip().str.lower().str.replace(' ', '_')
    data['area'] = pd.to_numeric(data['area'], errors='coerce')
    data['population'] = pd.to_numeric(data['population'], errors='coerce')
    return data

In [105]:
cleaned_data()

              country     capital    region  ... population  iso2  iso3
0           Lithuania     Vilnius    Europe  ...    2794700    LT   LTU
1               Chile    Santiago  Americas  ...   19116209    CL   CHL
2               Benin  Porto-Novo    Africa  ...   12123198    BJ   BEN
3    Falkland Islands     Stanley  Americas  ...       2563    FK   FLK
4             Georgia     Tbilisi      Asia  ...    3714000    GE   GEO
..                ...         ...       ...  ...        ...   ...   ...
245         Palestine   Jerusalem      Asia  ...    4803269    PS   PSE
246            Russia      Moscow    Europe  ...  144104080    RU   RUS
247        Azerbaijan        Baku      Asia  ...   10110116    AZ   AZE
248      South Africa    Pretoria    Africa  ...   59308690    ZA   ZAF
249            Turkey      Ankara      Asia  ...   84339067    TR   TUR

[250 rows x 8 columns]

In [134]:
#Clean data1 api data
def cleaned_data1(data1=data1()):
    data1 = data1.drop_duplicates()
    data1.columns = data1.columns.str.strip().str.lower().str.replace(' ', '_')
    data1['latitude'] = pd.to_numeric(data1['latitude'], errors='coerce')
    data1['longitude'] = pd.to_numeric(data1['longitude'], errors='coerce')
    data1 = data1.rename(columns={'name': 'country', 'capitalcity': 'capital'})
    data1 = data1.drop(columns=[
    'adminregion.id', 'adminregion.iso2code', 'adminregion.value',
    'region.id', 'region.iso2code',
    'incomelevel.id', 'incomelevel.iso2code',
    'lendingtype.id', 'lendingtype.iso2code'
])
    return data1

In [135]:
cleaned_data1()

     id iso2code  ...    incomelevel.value lendingtype.value
0   ABW       AW  ...          High income    Not classified
1   AFE       ZH  ...           Aggregates        Aggregates
2   AFG       AF  ...           Low income               IDA
3   AFR       A9  ...           Aggregates        Aggregates
4   AFW       ZI  ...           Aggregates        Aggregates
5   AGO       AO  ...  Lower middle income              IBRD
6   ALB       AL  ...  Upper middle income              IBRD
7   AND       AD  ...          High income    Not classified
8   ARB       1A  ...           Aggregates        Aggregates
9   ARE       AE  ...          High income    Not classified
10  ARG       AR  ...  Upper middle income              IBRD
11  ARM       AM  ...  Upper middle income              IBRD
12  ASM       AS  ...          High income    Not classified
13  ATG       AG  ...          High income              IBRD
14  AUS       AU  ...          High income    Not classified
15  AUT       AT  ...          High income    Not classified
16  AZE       AZ  ...  Upper middle income              IBRD
17  BDI       BI  ...           Low income               IDA
18  BEA       B4  ...           Aggregates        Aggregates
19  BEC       B7  ...           Aggregates        Aggregates
20  BEL       BE  ...          High income    Not classified
21  BEN       BJ  ...  Lower middle income               IDA
22  BFA       BF  ...           Low income               IDA
23  BGD       BD  ...  Lower middle income               IDA
24  BGR       BG  ...          High income              IBRD
25  BHI       B1  ...           Aggregates        Aggregates
26  BHR       BH  ...          High income    Not classified
27  BHS       BS  ...          High income    Not classified
28  BIH       BA  ...  Upper middle income              IBRD
29  BLA       B2  ...           Aggregates        Aggregates
30  BLR       BY  ...  Upper middle income              IBRD
31  BLZ       BZ  ...  Upper middle income             Blend
32  BMN       B3  ...           Aggregates        Aggregates
33  BMU       BM  ...          High income    Not classified
34  BOL       BO  ...  Lower middle income              IBRD
35  BRA       BR  ...  Upper middle income              IBRD
36  BRB       BB  ...          High income              IBRD
37  BRN       BN  ...          High income    Not classified
38  BSS       B6  ...           Aggregates        Aggregates
39  BTN       BT  ...  Lower middle income               IDA
40  BWA       BW  ...  Upper middle income              IBRD
41  CAA       C9  ...           Aggregates        Aggregates
42  CAF       CF  ...           Low income               IDA
43  CAN       CA  ...          High income    Not classified
44  CEA       C4  ...           Aggregates        Aggregates
45  CEB       B8  ...           Aggregates        Aggregates
46  CEU       C5  ...           Aggregates        Aggregates
47  CHE       CH  ...          High income    Not classified
48  CHI       JG  ...          High income    Not classified
49  CHL       CL  ...          High income              IBRD

[50 rows x 9 columns]

In [136]:
#Merge data and data 1 together
def merged():
    data = cleaned_data()
    data1 = cleaned_data1()
    merged = pd.merge(data, data1, on='country', how='inner')
    return merged

In [137]:
merged()

                     country  ... lendingtype.value
0                      Chile  ...              IBRD
1                      Benin  ...               IDA
2                    Belgium  ...    Not classified
3                    Andorra  ...    Not classified
4                  Argentina  ...              IBRD
5                     Belize  ...             Blend
6                 Bangladesh  ...               IDA
7                Afghanistan  ...               IDA
8                   Bulgaria  ...              IBRD
9       United Arab Emirates  ...    Not classified
10  Central African Republic  ...               IDA
11                   Austria  ...    Not classified
12                    Bhutan  ...               IDA
13                    Brazil  ...              IBRD
14                    Angola  ...              IBRD
15                     Aruba  ...    Not classified
16                 Australia  ...    Not classified
17                  Botswana  ...              IBRD
18                   Albania  ...              IBRD
19            American Samoa  ...    Not classified
20                   Bolivia  ...              IBRD
21                   Burundi  ...               IDA
22                   Bahrain  ...    Not classified
23                    Canada  ...    Not classified
24              Burkina Faso  ...               IDA
25       Antigua and Barbuda  ...              IBRD
26                  Barbados  ...              IBRD
27                   Belarus  ...              IBRD
28                   Bermuda  ...    Not classified
29    Bosnia and Herzegovina  ...              IBRD
30               Switzerland  ...    Not classified
31                   Armenia  ...              IBRD
32                Azerbaijan  ...              IBRD

[33 rows x 16 columns]

In [138]:
#convert merged data to a csv
merged = merged()
merged.to_csv('merged_data.csv')